GET http://114.116.51.209:80/ajax/branch?committee=三甲镇党委
Accept: application/json

###
GET http://101.200.231.235 :80/ajax/branch?committee=三甲镇党委
Accept: application/json

###
POST http://localhost:8080/api/login1
Content-Type: application/json

{
  "username": 123,
  "password": 456
}

###
